---
# file: tasks/section-01.yml

- name: 1.1 Install Updates, Patches and Additional Security Software (Not Scored)
  apt: upgrade=dist update_cache=yes
  tags:
    - notscored
    - section1.1

- name: Check if reboot is required
  shell: if [[ $(readlink -f /vmlinuz) != /boot/vmlinuz-$(uname -r) ]]; then echo "reboot required"; else echo "no"; fi
  register: reboot_required
  tags:
    - notscored
    - section1.1

- name: Reboot host to apply updates
  reboot:
    reboot_timeout: 3600
  tags:
    - notscored
    - section1.1


# vim: set sw=2 ts=2:
